### ISSUE TITLE
Player count wrong (impossible values)

### ISSUE THREAD

**Issue by MrMois** [Dendari92/bblog-true-players-bf3#1]
Thanks for the nice plugin, I really appreciate it!

However, since a few days a bug is occurring, where the improved player count shows higher numbers than correct. Interestingly these numbers are even higher than the highest possible player count.

Do you know what causes this?

Greetings!

**Comment by Dendari92** [comment]
Hi, sorry for the late reply.

I don't know what causes it, I'll try to investigate and report back if I find something.

The plugin uses the same API used by Battlelog when you click on "Show all players", so it could be a temporary bug (or might be permanent considering EA/DICE stopped supporting BF3 a long time ago).

**Comment by Dendari92** [comment]
**UPDATE: I've released a new beta version, here's the link with instructions https://github.com/Dendari92/bblog-true-players-bf3/releases/tag/v1.2-beta**

It seems the Battlelog API is broken currently on some server and it shows players which probably left the server as still inside. I've added a toggle in the BBLog settings to filter only "real" playing players, it has one downside though: players with status set to invisible aren't counted.

For now I'm releasing this as a beta version as I don't have much time to do some testing, so any feedback is appreciated.

**Comment by MrMois** [comment]
Thanks for looking into this! It's strange API stuff changes after so many years, but I guess EA is reducing resources to a bare minimum. 

I will try out the beta version and report back how it works in the future.

**Comment by Dendari92** [comment]
Hi. Have you tried the beta version? Noticed any issue?

**Comment by Dendari92** [comment]
Hello. The beta version v1.2 has been released out of beta. Let me know of any issue.

**Comment by doom-hamster** [comment]
> Hello. The beta version v1.2 has been released out of beta. Let me know of any issue.

Works like a charm in Favorites! Thanks a lot.

And the new setting to count only people who are online and playing - is a good workaround to whatever the hell is going on with battlelog (seen impossible player counts, like 70-100). Even if it shows a little less due to invisible status players, a lesser estimate is still much better than being jebaited w/o this feature enabled. This setting should be enabled by default imo.
Does this setting sees in which server a player is playing at the moment, or does it just checks the blue "playing" status?

Lastly, this update deserves a new reddit post from you on r/Battlefield 3.
You can list this BBL version for firefox (easy to install):
https://addons.mozilla.org/ru/firefox/addon/better-battlelog-fix-bblog/
i use it with no problems.

**Comment by MrMois** [comment]
Hey, I used the beta 1.2 since April and now I updated to the new release version. However, in both versions I still got the same bug as before, with some servers showing a too high player count (e.g. "64 [84] / 64").

**Comment by MrMois** [comment]
I am using the latest Firefox version and tried clearing the website's cache, but nothing changed.

**Comment by Dendari92** [comment]
That's unfortunate to hear. Would you mind sharing some of the servers names you see this behaviour? Hopefully it'd allow me to better understand what's wrong.

**Comment by MrMois** [comment]
Shure. Unfortunately, there are currently only a few players in the game. Since the bug only occurs on servers with a large number of players, I do not have many examples. Yet here are two:
![player-count](https://user-images.githubusercontent.com/43606051/171263052-b120a90e-e6df-4559-ae3e-7bf462d39f3b.png)

**Comment by doom-hamster** [comment]
> Shure. Unfortunately, there are currently only a few players in the game. Since the bug only occurs on servers with a large number of players, I do not have many examples. )

Are you sure you enabled the option "Filter only real playing players" in BetterBattleLog settings?
 
![изображение](https://user-images.githubusercontent.com/106200718/171374645-ad95ee45-9da5-40c2-8386-d32969e796e6.png)

Also try this BBL version: https://addons.mozilla.org/en-US/firefox/addon/better-battlelog-fix-bblog/

**Comment by MrMois** [comment]
> Are you sure you enabled the option "Filter only real playing players" in BetterBattleLog settings?

This did the trick for me, thank you!
