### ISSUE TITLE
Suggestion: make it work in "Favorites" tab

### ISSUE THREAD

**Issue by doom-hamster** [Dendari92/bblog-true-players-bf3#2]
First, thank you for this great plugin, such a qol improvement to be able to see empty or half filled servers much faster (than checking every server individually).

But i'd like to see the same feature in Favorite servers tab. Favorites tab is nice, where one can save popular servers with different gamemodes, and join one that is populated at the moment. Instead of refreshing Server Browser where a ton of servers shows up, most of them just clutter the screen with something like 64[0 real]/64 players.

**Comment by Dendari92** [comment]
Hello! I'll be working on this in the next few days, it shouldn't take long (just need to find some free time). Will report back to you when it's done.

**Comment by Dendari92** [comment]
Hello, a new update has been released with your request implemented. Let me know of any issue.

**Comment by doom-hamster** [comment]
> Hello, a new update has been released with your request implemented. Let me know of any issue.

Works like a charm in Favorites! Thanks a lot.

And the new setting to count only people who are online and playing - is a good workaround to whatever the hell is going on with battlelog (seen impossible player counts, like 70-100). Even if it shows a little less due to invisible status players, a lesser estimate is still much better than being jebaited w/o this feature enabled. This setting should be enabled by default imo.
Does this setting sees in which server a player is playing at the moment, or does it just checks the blue "playing" status?

Lastly, this update deserves a new reddit post from you on r/Battlefield 3.
You can list this BBL version for firefox (easy to install):
https://addons.mozilla.org/en-US/firefox/addon/better-battlelog-fix-bblog/
i use it with no problems.

**Comment by Dendari92** [comment]
Hi. Thanks for the great feedback.

> This setting should be enabled by default imo.

I'll definitely think about it. Currently I'm kinda hoping the Battlelog API will start working correctly again some time in the future, as imo the workaround it's not ideal.

> Does this setting sees in which server a player is playing at the moment, or does it just checks the blue "playing" status?

The "Show all players" Battlelog API returns quite a bit of information, such as players names, their ranks, their status, etc. The workaround is to get only players with their status set to "playing".

> Lastly, this update deserves a new reddit post from you on r/Battlefield 3

I want to be sure it's working correctly, unfortunately I'm not playing BF3 much these days so I can't test it myself.

> You can list this BBL version for firefox (easy to install):
> https://addons.mozilla.org/ru/firefox/addon/better-battlelog-fix-bblog/

Okay, thanks. I've not used it myself so I'm gonna give a try. I'll add it as an alternative method when installing the plugin.
