### ISSUE TITLE
Some servers use fake bot names

### ISSUE THREAD

**Issue by FreddieDev** [Dendari92/bblog-true-players-bf3#3]
For example, see: https://battlelog.battlefield.com/bf3/servers/show/pc/e746eba6-4e93-4310-b14f-a0f55332a9ec/TNT-1-GULF-OF-OMAN-Conquest-discord-tnt-community/

Here, you can see bots use fake names with auto-generated characters:
![image](https://user-images.githubusercontent.com/4047565/191324098-9f361e2a-80e7-42d4-85b9-db4780134954.png)

After reading the source, it's clear you can use Regex to filter these - great!

For anyone who reads this, I used: `YR_PRSNL_.*`
Perhaps this could be added to the readme? It's a great feature.

Many thanks for all your work, this plugin is essential

**Comment by Dendari92** [comment]
Hi, glad you like the plugin and the feature!

Btw it is mentioned in the README under "**Known Issues and Limitations**".

https://github.com/Dendari92/bblog-true-players-bf3#filter-fake-accounts-inside-a-server

😊

**Comment by FreddieDev** [comment]
Ah, I was referring to it being capable of handling wildcards and regex specifically, made it really useful for all those bots with very similar names

**Comment by Dendari92** [comment]
Ah sorry, yes you're right. I'm adding a note about it, thanks!
